name: Check Code Format

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:
    inputs:
      testdir:
        default: 'tests'
        required: false
        type: string
      srcdir:
        default: 'src'
        required: false
        type: string

jobs:
  lint_in_actions:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort

    - name: isort
      run: |
        isort ${{ inputs.srcdir }} ${{ inputs.testdir }} --diff --check

    - name: flake8
      run: |
        flake8 ${{ inputs.srcdir }} ${{ inputs.testdir }}

    - name: black
      run: |
        black ${{ inputs.srcdir }} ${{ inputs.testdir }} --diff
